debug: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kafka_lbs?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: zM/183596206579
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  kafka:
    bootstrap-servers: localhost:9092

knife4j:
  enable: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: statement
  global-config:
    banner: false
    db-config:
      id-type: auto

amap:
  key: d3bfb79aa31667bd58f475ac63b98611
